services:
  app:
    image: etma:1
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://db_user:db_password@cluster.dldgv.mongodb.net/express-ts-mingoose-auth
      - JWT_SECRET=your_jwt_secret
