apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  jwt_secret: eW91cl9qd3Rfc2VjcmV0Cg==
  db_uri: bW9uZ29kYitzcnY6Ly9kYl91c2VyOmRiX3Bhc3N3b3JkQGNsdXN0ZXIuZGxkZ3YubW9uZ29kYi5uZXQvZXhwcmVzcy10cy1taW5nb29zZS1hdXRoCg==
