apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: etma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etma
  template:
    metadata:
      labels:
        app: etma
    spec:
      containers:
        - name: etma
          image: wahideng/etma:1.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: jwt-secret
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db_uri
