name: Continuous Deployment

on:
  pull_request:
    types:
      - closed # Trigger when a PR is closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the version number using the run number
      - name: Set version
        id: set_version
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          VERSION="1.0.0-build.${BUILD_NUMBER}"
          echo "VERSION=$VERSION"
          echo "name=version::${VERSION}" >> $GITHUB_OUTPUT

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.set_version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Login to Docker registry (Docker Hub or other registries)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/etma:${{ steps.set_version.outputs.version }} .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/etma:${{ steps.set_version.outputs.version }}
