name: Continuous Deployment

on:
  pull_request:
    types:
      - closed # Trigger when a PR is closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/etma:v${{ github.event.number }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/etma:v${{ github.event.number }}
