name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Tests (for example, using npm for Node.js services)
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 3000

      # Make sure no error during build image

      - name: Docker Image Metadata
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/etma

      # Login to Docker registry (Docker Hub or other registries)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build and Push Docker Image with Timestamp
        run: |
          echo "${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
